### ISSUE TITLE
dbo:procedure toevoegen aan applicatieprofiel

### ISSUE THREAD

**Issue by gezever** [Informatievlaanderen/OSLOthema-dossier#5]
Zoals gevraagd in de presentatie voor de datastandaarden werkgroep.

![Screenshot from 2023-08-31 09-49-55](https://github.com/Informatievlaanderen/OSLOthema-dossier/assets/28095014/3b631a53-c7a5-4370-8d51-08ffb4d0edf0)

**Comment by saxomoose** [comment]
https://github.com/Informatievlaanderen/OSLOthema-dossier/releases/tag/erkend-2023-09-25
